version: "3"

services:
  backend:
    image: backvuolei
    hostname: backvuolei
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    network_mode: "host"
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: "postgres:13.3-alpine"
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      args:
        NUXT_PUBLIC_PATH: http://localhost/static/
    image: frontvuolei
    hostname: frontvuolei
    command: npm run dev
    network_mode: "host"
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - nginx

  nginx:
    image: nginx
    hostname: nginxvuolei
    network_mode: "host"
    volumes:
      - ./data:/dkdata
    ports:
      - 81:80
    environment:
      NGINX_SITE: local

volumes:
  postgres_data:
